KRX_BASE_URL="https://data-dbg.krx.co.kr/svc/apis/etp/etf_bydd_trd"
KRX_AUTH_KEY="9BD04E0288594171B1DB385D2D802AF569C6D7D6"
DATA_GO_URL="https://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo"
DATA_GO_ETF_URL = "https://apis.data.go.kr/1160100/service/GetSecuritiesProductInfoService"
DATA_GO_SERVICE_KEY = "LQqfPahJp7MHaNrC7j9QIRbk2zEnMGOfDVZZ8wTr+IMXBsKag/RZ/cVqMBSeNMdxWu7NCnfnth7LsifQXjcrxw=="
